package com.kerux.SevletRootAdmin;

import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.kerux.bean.RatingBean;
import com.kerux.security.Security;
import com.kerux.utility.DBUtility;

/**
 * Servlet implementation class PDFrating
 */
@WebServlet("/PDFrating")
public class PDFrating extends HttpServlet implements DBUtility {

	private static Connection getConnection(){
		Connection connection = null;
		
		try{
			Class.forName(Security.decrypt(jdbcDriverName)); //ensure that the library will be loaded to the memory
			//secure database connection string configuration
			connection = DriverManager.getConnection(Security.decrypt(jdbcUrl),
					Security.decrypt(dbUserName),Security.decrypt(dbPassword));
			
		}catch(ClassNotFoundException cfne){
			//should be displayed on a secure error page code
			System.err.println(cfne.getMessage());
		}catch(SQLException sqle){
			System.err.println(sqle.getMessage());
		}
		return connection;
	}
	
	

protected void processRequest(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

    response.setContentType("application/pdf");
    //
    
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	Date date = new Date();
	String timeStamp=formatter.format(date);
    
    
	
  
    OutputStream out=response.getOutputStream();
    try {
        Document document = new Document();
        /* Basic PDF Creation inside servlet */
        PdfWriter.getInstance(document, out);
        document.open();
        document.add(new Paragraph("KERUX RATING REPORT"));
        document.add(new Paragraph(timeStamp));
        document.add(new Paragraph("Report generated by: Roy Christian Yabut"));
        document.add(new Paragraph("**********"));
        
        try{
			Connection connection = getConnection();
			
			PreparedStatement ps=connection.prepareStatement(SELECT_AVE_RATING);
			ResultSet rs=ps.executeQuery();
			while(rs.next()) {
				document.add(new Paragraph("AVERAGE RATING: " + rs.getString(1)+" / 5"));
			}

		}catch(Exception e){e.printStackTrace();}
        document.add(new Paragraph("**********"));
        
        PdfPTable table = new PdfPTable(4); 
        table.setWidthPercentage(100);
        PdfPCell cell9 = new PdfPCell(new Paragraph("Rating"));
        PdfPCell cell10 = new PdfPCell(new Paragraph("Patient Name"));
        PdfPCell cell11 = new PdfPCell(new Paragraph("Queue Name"));
        PdfPCell cell12 = new PdfPCell(new Paragraph("Time Stamp"));


        table.addCell(cell9);
        table.addCell(cell10);
        table.addCell(cell11);
        table.addCell(cell12);



        try{
			Connection connection = getConnection();
			Security sec = new Security();
			PreparedStatement ps=connection.prepareStatement(SELECT_RATING);
			ResultSet rs=ps.executeQuery();
			while(rs.next()) {
				

				
				PdfPCell cell1 = new PdfPCell(new Paragraph(rs.getString(2)));
				PdfPCell cell2 = new PdfPCell(new Paragraph(rs.getString(4)+", "+rs.getString(3)));
				PdfPCell cell3 = new PdfPCell(new Paragraph(rs.getString(5)));
				PdfPCell cell4 = new PdfPCell(new Paragraph(rs.getString(6)));

				table.addCell(cell1);
		        table.addCell(cell2);
		        table.addCell(cell3);
		        table.addCell(cell4);

				
			}
			
			

		}catch(Exception e){e.printStackTrace();}
        
        
        

       

        document.add(table);
        
        document.close();
    }
            catch (DocumentException exc){
            throw new IOException(exc.getMessage());
            }
    finally {            
        out.close();
    }
}
@Override
protected void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {
    processRequest(request, response);
}
@Override
protected void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {
    processRequest(request, response);
}

@Override
public String getServletInfo() {
    return "This Servlet Generates PDF Using iText Library";
}





}